# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81b3975a22e79a94e71ee647c367f74c536f5ac066d8aa36494a6491b00c278f4b5e4c13d8efe7db8ca5141842da8a0f8305dc2309d18ce177756642899e1efa

test:
  secret_key_base: 9f87543cca1db9f707350a7641b24fa1bf2856eeba7b189061c9d0cb1d03d71eed070fbc19020f68389a23db3eded4a60f259eba504035a0f2637b01ec9bbfe5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
